### ISSUE TITLE
Harvester Tab - Avg Eligible Plots

### ISSUE THREAD

**Issue by aDilly** [grayfallstown/Chia-Plot-Status#100]
I have 302 eligible plots currently being farmed.
Chia GUI is showing a small number of plots passing the filter (0-3), as does the log file.

Avg eligible plots is still showing 0.00000
I pulled the log and calculated my average (mean) of the last ~2000 plot filter checks to be 0.58
Is there anyway I can confirm what the issue is here? Any other info I can provide?

5x K33 Plots
297x K22 Plots

![Attempted Proofs - GUI](https://user-images.githubusercontent.com/77657714/121997857-d8557b00-cd5f-11eb-8657-df32dfb1ae88.png)
![harvesters health](https://user-images.githubusercontent.com/77657714/121997860-d8ee1180-cd5f-11eb-94a7-9fbbb4107611.png)

**Comment by grayfallstown** [comment]
Hi, thanks for reporting. I just released 0.11.5 with a fix. Please update.

**Comment by aDilly** [comment]
Confirmed its fixed - Awesome stuff - Thanks!
