### ISSUE TITLE
error extracting json by cmd

### ISSUE THREAD

**Issue by Hatt3rPi** [grayfallstown/Chia-Plot-Status#103]
Hi, I have been developing a little code that checks the new plots in the destination folder, and extracts a Chia Plot Status json file by cmd.

the problem occurred when i updated to version 0.11.7

I get the following error: 
![image](https://user-images.githubusercontent.com/11076084/122858258-fe42c880-d2e7-11eb-8c46-57ed26d315f0.png)

Should I change / add any parameters?

**Comment by grayfallstown** [comment]
Please update to 0.11.8 as this was a bug in the code.

May I ask, what are you using the cli for?

**Comment by Hatt3rPi** [comment]
![image](https://user-images.githubusercontent.com/11076084/122925583-f8270900-d334-11eb-8d3c-567f15270e86.jpeg)
![image](https://user-images.githubusercontent.com/11076084/122925784-2c022e80-d335-11eb-808e-5d4ca577e0f2.jpeg)

As an enthusiast, I am preparing a telegram bot to notify me when a new plot is generated, daily summary, plot analysis, recommendations among others.. 
I use ChiaPlotStatus to collect data from the creation of each plot, for example the durations of the different phases.

**Comment by grayfallstown** [comment]
@Hatt3rPi Great project!

I love to see how people use the software.
