### ISSUE TITLE
Could you make it work for Flax too?

### ISSUE THREAD

**Issue by nanohtpc** [grayfallstown/Chia-Plot-Status#104]
hello again..

I was testing, works but not in all the columns, with adjustments it could.. could you please? 8)))

**Comment by grayfallstown** [comment]
More details please

**Comment by nanohtpc** [comment]
https://flaxnetwork.org

Flax its a fork of chia.. it can farm using the plots of chia, even create new ones, but its a lot faster, today  i won 2 flax (XFX), so i added the dir to your app, , it can be read, but in some columns doesnt show the correct info...

**Comment by grayfallstown** [comment]
Which Columns?
Can you provide a logfile?

**Comment by nanohtpc** [comment]
[
[plotter_log_e6c409a9-1b32-4348-9b2a-6742f5783793.txt](https://github.com/grayfallstown/Chia-Plot-Status/files/6711205/plotter_log_e6c409a9-1b32-4348-9b2a-6742f5783793.txt)
](url)

please delete after dl, from here.. 8)))

**Comment by grayfallstown** [comment]
> but in some columns doesnt show the correct info...

so which columns are it?

**Comment by nanohtpc** [comment]
well after the plots end its fixed itself!!!... strange...
