### ISSUE TITLE
[issue] i can't open the program in windows 10

### ISSUE THREAD

**Issue by ari2asem** [grayfallstown/Chia-Plot-Status#110]
i am happy user of this program in windows 10, since version 0.9.xxx.

but since 2 days i can't run the program. when i double-click to run the program, i can see in TASK MANAGER that it loads, but then closes without any error.

2 days ago i tried to export my logs to CSV format. this went wel. after opening the CSV inside LibreOffice, i got my computer very very slow...i  dont know what i did at that moment, but after this program is not running.

i even unistalled, reboot the computer, re-install differen versions....no help. it keeps closing without error.

any help ?? i love  this program, very wonderful to see lots of stats....

**Comment by grayfallstown** [comment]
I tried to reproduce the Issue, but had no luck so far.

Here is what you can try:
1. Confirm that ChiaPlotStatus is not running by using the Task Manager
2. Go into your user profile folder (C:\\Users\<your-username>\)
3. Rename ChiaPlotStatus.cache.json to ChiaPlotStatus.cache.json.bak
4. Try to start Chia Plot Status (With the caches deleted, the application start can take a lot longer than you are used to)

It that fails:
- Repeat steps 1, 2 and 3
- Rename ChiaPlotStatu.config.json to ChiaPlotStatu.config.json.bak (in your user profile folder, just like ChiaPlotStatus.cache.json)
- Try to start again

**Comment by ari2asem** [comment]
i can confirm that renameing json-file helped me....great solution. thank you very much :)
