### ISSUE TITLE
"Text File Busy"

### ISSUE THREAD

**Issue by jokerxshot** [grayfallstown/Chia-Plot-Status#115]
I'm trying to extract the log files from MadMax plotter to use in the GUI and whenever I enter in the command to do so (as instructed in the documentation), it spits out an error saying that both text files are busy? I am running Ubuntu, Linux with Mad Max Plotter.

**Comment by grayfallstown** [comment]
To clarify, you are using the CLI to run madmax and add the `tee` command to write the logs to a file like this: `chia-plotter [your parameters here] 2>&1 | tee /home/$(whoami)/.chia/mainnet/plotter/chia-plotter-$(uuid).log;` and then get an error? Do you get the error from the tee command or from madmax itself?

Or do you mean you run the ChiaPlotStatusCLI and try to export the already existing logs to json, yaml or csv files using it?

Can you paste the log or command line output here?

**Comment by jokerxshot** [comment]
Bear with me as I am new to all of this but I don't think I have Mad Max configured to be outputting any log files automatically. Is there a command to do so? I have just been using the commands in the documentation on GitHub in the normal Linux CLI. 

This is the log from the CLI (it's not normally all one command but copy and pasting it all makes it that way)
```

wee@wee:~/Chia-Plot-Status$ export POOLKEY="82bcfedf655030dd5fb7bbd0902557b8a3e23e0d2eff5e4105d04fc9b021ee44d5f71b09feb99640686d82fe58be1b24"; > export FARMERKEY="b2f55b35f4f4340d0c76bac2340aff0c7482d31bc122a71b017a044794121678ebcf16925a38427677ee366620c815d8"; > export THREADS="$(expr $(nproc) / 2)"; > /home/wee/chia-plotter/build/chia_plot > --poolkey=$POOLKEY > --farmerkey=$FARMERKEY > --tmpdir2=/media/wee/tmp/tmp/ > --tmpdir=/media/wee/tmp/tmp/ > --finaldir=/media/wee/yeee/final/ > --count=-1 > --threads=$THREADS export POOLKEY="82bcfedf655030dd5fb7bbd0902557b8a3e23e0d2eff5e4105d04fc9b021ee44d5f71b09feb99640686d82fe58be1b24"; > export FARMERKEY="b2f55b35f4f4340d0c76bac2340aff0c7482d31bc122a71b017a044794121678ebcf16925a38427677ee366620c815d8"; > export THREADS="$(expr $(nproc) / 2)"; > /home/wee/chia-plotter/build/chia_plot > --poolkey=$POOLKEY > --farmerkey=$FARMERKEY > --tmpdir2=/media/wee/tmp/tmp/ > --tmpdir=/media/wee/tmp/tmp/ > --finaldir=/media/wee/yeee/final/ > --count=-1 > --threads=$THREADS 2>&1 | tee /home/wee/.chia/mainnet/plotter/chia-plotter-$(uuid).log;
bash: /home/wee/chia-plotter/build/chia_plot: Text file busy
bash: /home/wee/chia-plotter/build/chia_plot: Text file busy
wee@wee:~/Chia-Plot-Status$ 
```

**Comment by grayfallstown** [comment]
There are a lot of larger than symbols between the parameters that don't belong there:
`tmp/ > --finaldir=/media/wee/yeee/final/ > --count=-1 > --threads`
Get rid of all of them, except that one:
`--threads=$THREADS 2>&1 | tee `

**Comment by jokerxshot** [comment]
Ohh so I need to run this command to start up the miner I can't run this with it already running gotcha. It's working now, thank you!
