### ISSUE TITLE
Download link is broken

### ISSUE THREAD

**Issue by tajchert** [grayfallstown/Chia-Plot-Status#13]
Hi,
After clicking 'Download latest version patient-farmer' with a link https://github.com/grayfallstown/Chia-Plot-Status/blob/main/Setup.exe - I get 404 and blob link seems to be broken.

**Comment by grayfallstown** [comment]
Fixed, thank you very much

**Comment by tajchert** [comment]
Thank you! I didn't know the proper URL so didn't do a PR. Thanks!
