### ISSUE TITLE
Add Date Started / Date Finished to order plot logs

### ISSUE THREAD

**Issue by rul3s** [grayfallstown/Chia-Plot-Status#19]
Hi!
If posible could you add two columns [Date Started, Date Finished] to be able to order by them? So we can easily find data from last finished plots and compare.

Thanks!

**Comment by grayfallstown** [comment]
Ok, should be in the next version

**Comment by grayfallstown** [comment]
Done: [Setup.exe](https://grayfallstown.github.io/Chia-Plot-Status/Setup.exe)

**Comment by rul3s** [comment]
Wow, so fast! Very apreciated men ;)

**Comment by rul3s** [comment]
> Done: [Setup.exe](https://grayfallstown.github.io/Chia-Plot-Status/Setup.exe)

I've tried it and I could install it but then I can't launch it. I tried installing over the last version and also uninstalling and installing it again. Also, Icon is not showing in desktop neither Start Menu.

Can you check it?

**Comment by grayfallstown** [comment]
checking it

**Comment by grayfallstown** [comment]
Try to delete `C:\Program Files (x86)\ChiaPlotStatus\ChiaPlotStatus\ChiaPlotStatus.dll.config.json`

Its the only thing I can think of

**Comment by grayfallstown** [comment]
Accidentally shipped my local configuration as part of the release and bug caused chia plot status to crash on startup when it tried to find plotlogs in `my` home dir on `your` computer

**Comment by rul3s** [comment]
Exactly! After deleting config file it works. Icon still missing and when changing from light to dark it crashes, but now its working.

Thanks!

**Comment by grayfallstown** [comment]
Icon should be there if you re-download and install chia plot log again.

It crashes when you switch to dark mode? Can you check if this still happens with the latest version?

**Comment by rul3s** [comment]
With last installer everything works, icon, darkmode and config, just perfect.

Thanks ;)

**Comment by grayfallstown** [comment]
You are welcome
