### ISSUE TITLE
Add additional log directory crashes application

### ISSUE THREAD

**Issue by TormodSan** [grayfallstown/Chia-Plot-Status#21]
* Start ChiaPlotStatus.exe
* Press "Add" button 

EXPECTED: new directory is added and scanned
ACTUAL: application freezes and then closes.

**Comment by grayfallstown** [comment]
Does the directory contain files that are not logs and possibly quite large?
Do you have read access on the files?
Are the log files on a network share?
Did you test the lastest version? (published about 7 minutes ago)

**Comment by grayfallstown** [comment]
Does it do the same if you change to dark mode?

In that case you don't have write access on the installation directory

**Comment by TormodSan** [comment]
Not sure which version I have: exe has 219 648 Bytes. - You should add "About"
Same when switching to dark mode.

Yes permissons is the problem:
Since it is located in C:\Program Files (x86)\ChiaPlotStatus\ChiaPlotStatus it requires Admin rights to change files in there.

I think you need to place the config files somewhere else, don't think people like to "run it as Administrator"

**Comment by grayfallstown** [comment]
currently building an update

**Comment by grayfallstown** [comment]
[Latest version](https://grayfallstown.github.io/Chia-Plot-Status/Setup.exe) puts the config file in user profile directory.

I will add a button for an update check and a version number

**Comment by TormodSan** [comment]
Working fine, thanks
