### ISSUE TITLE
[Minor] Line height option

### ISSUE THREAD

**Issue by bathrobehero** [grayfallstown/Chia-Plot-Status#22]
Minor thing but I'd much more prefer the older line height as it showed more info for the same space:

![image](https://user-images.githubusercontent.com/6293506/117338721-3066ab00-ae9f-11eb-8c18-e1e05564335e.png)

Maybe we can get a config file we can edit to customize it?

Also, I love this tool! Do you have any donation options, would love to send a couple of beers your way.

**Comment by grayfallstown** [comment]
> Minor thing but I'd much more prefer the older line height as it showed more info for the same space:
> Maybe we can get a config file we can edit to customize it?

No need for a config file, this change was unintentional. Did not notice it, was too focused on implementing a feature.
Will fix it in a moment

> Also, I love this tool!

Love to hear it!

> Do you have any donation options, would love to send a couple of beers your way.

I love beer! You could send me a fraction of a chia coin: xch1sxgmrrmq95klztd5796ysz8c6jattd6k70z4gxuet5a9792s24hqf4jdtn
Alternativly there is always paypal: maklemenz@googlemail.com

**Comment by grayfallstown** [comment]
[Latest release](https://github.com/grayfallstown/Chia-Plot-Status/releases/tag/0.9.6-beta6) should fix that

**Comment by bathrobehero** [comment]
That was fast! Cheers!

**Comment by bathrobehero** [comment]
That was fast! Cheers!

**Comment by grayfallstown** [comment]
> That was fast! Cheers!

Cheers and thx a lot
