### ISSUE TITLE
Can't read some log files.

### ISSUE THREAD

**Issue by supakiat-sean** [grayfallstown/Chia-Plot-Status#24]
It's working normal after that I removed error log files then ploting new file and run "Chia-Plot-Status" again. It not working. but It show complete plot files log.

**Comment by grayfallstown** [comment]
What do you mean with it is not working? Does it not show running plots unless finished?
By removing Error logs you mean deleted the files or did you mark them as dead by clicking on the error?
Could you please post a screenshot so I can see what you mean?

**Comment by supakiat-sean** [comment]
Now it only show done plot log but not show undone log not in list.

ในวันที่ ศ. 7 พ.ค. 2021 13:27 น. grayfallstown ***@***.***>
เขียนว่า:

**Comment by grayfallstown** [comment]
Do you have any filters on?

![Screenshot2](https://user-images.githubusercontent.com/50076933/117407722-3c8a5100-af0f-11eb-928f-1b98a26061de.JPG)

Could you please copy one of the logs in here that are running but not shown?

**Comment by supakiat-sean** [comment]
Done log is 203 KB and running plot 76,92 KB

ในวันที่ ศ. 7 พ.ค. 2021 13:37 น. grayfallstown ***@***.***>
เขียนว่า:

**Comment by grayfallstown** [comment]
I need more information than this

**Comment by grayfallstown** [comment]
The Log file contains an ID:
```
Starting plotting progress into temporary dirs: d:\PlotTemp and p:\PlotTemp
ID: XXX
Plot size is: 32
Buffer size is: 3750MiB
Using 128 buckets
Final Directory is: M:\Plot
```

Search and replace it with XXX (is is printed multiple times in the log) and you can safely post it on the internet.

**Comment by supakiat-sean** [comment]
I try copy done log and not done log to the somewhere and add to program
but it read only done log.

ในวันที่ ศ. 7 พ.ค. 2021 14:01 น. grayfallstown ***@***.***>
เขียนว่า:

**Comment by grayfallstown** [comment]
I mean copy it on this website so i can test it here on my machine and see what is going on

**Comment by supakiat-sean** [comment]
It done.I can fix it by remove "Warning" line out of log. Thanks for your
attention.

ในวันที่ ศ. 7 พ.ค. 2021 14:17 น. grayfallstown ***@***.***>
เขียนว่า:

**Comment by grayfallstown** [comment]
Can you please tell me what warning line? I would like to fix it in the program.

**Comment by supakiat-sean** [comment]
Fix in log file by remove two lines like this.

ในวันที่ ศ. 7 พ.ค. 2021 14:23 น. grayfallstown ***@***.***>
เขียนว่า:
