### ISSUE TITLE
App reports plot as complete, but copy to -d is not fully done yet

### ISSUE THREAD

**Issue by TormodSan** [grayfallstown/Chia-Plot-Status#27]
Due to some reason, final plot can not be copied to target:
`Could not copy "d:\\chiatemp\\plot-k32-2021-05-07-09-00-....plot.2.tmp" to "\\\\192.168.178.157\\farm4\\plot-k32-2021-05-07-09-....plot.2.tmp". Error Unerwarteter Netzwerkfehler.. Retrying in five minutes.`

But app reports 100% and total time already for that plot

**Comment by grayfallstown** [comment]
Never had this error, so I couldn't handle it.
Will be fixed soon.

**Comment by grayfallstown** [comment]
Just released a fix
