### ISSUE TITLE
Hard to tell which one is the just-finished one

### ISSUE THREAD

**Issue by lilei105** [grayfallstown/Chia-Plot-Status#3]
This is a very useful tool. The only headache I have for now is, when I have plenty of logs, I cant tell which are the most recent ones. Would there be one more column like 'start time' in the next version? Sortable by column is also much appreciated.

**Comment by grayfallstown** [comment]
I'm currently busy switching the library I use to build the graphical interface to something that runs on Mac and Linux, too.

Starttime column will be added again. It somehow got missing when I reworked the data to be more readable.

Sortable Columns, Searching, Filter to hide finished or crashed plottin processes and highlighting crashed plots are planned.

**Comment by lilei105** [comment]
> I'm currently busy switching the library I use to build the graphical interface to something that runs on Mac and Linux, too.
> 
> Starttime column will be added again. It somehow got missing when I reworked the data to be more readable.
> 
> Sortable Columns, Searching, Filter to hide finished or crashed plottin processes and highlighting crashed plots are planned.

Thanks a lot, man. I'm counting on you.
