### ISSUE TITLE
display number of active plots

### ISSUE THREAD

**Issue by magnusmyklebost** [grayfallstown/Chia-Plot-Status#31]
as far as i can see the only way of seeing how many active plots you have is by counting. it would be great if you display at the top the total number of active plots and number of plots in each phase. i plot 14 in parallel now, and having to count 13-14 plots down to see if i need to start another is time consuming. 

great tool btw!

**Comment by grayfallstown** [comment]
Can you try downloading and installing the [Setup.exe](https://github.com/grayfallstown/Chia-Plot-Status/releases/download/0.9.7-beta3/Setup.exe) again?
![Screenshot](https://user-images.githubusercontent.com/50076933/117924810-9f585f80-b2f6-11eb-985f-d015e8037d61.JPG)

**Comment by magnusmyklebost** [comment]
cool. will test when i get back home. i downloaded via the update button and the version after update was the latest. 
thats great responstime btw, and the new functionality is exactly what i hoped for!
