### ISSUE TITLE
Windows Antivirus detects it as a Trojan

### ISSUE THREAD

**Issue by RedxLus** [grayfallstown/Chia-Plot-Status#32]
This is Windows Defender. He says Trojan. I have downloaded it from here, from the released section.

<a href="https://imgbb.com/"><img src="https://i.ibb.co/GMHrfk9/plot.png" alt="plot" border="0"></a>

**Comment by grayfallstown** [comment]
Thanks for the report. Do you now which version you downloaded by any chance?

**Comment by grayfallstown** [comment]
Reported this to microsoft. They have experts who can look at it and find out why it is being detected.

**Comment by grayfallstown** [comment]
setup.exe
Submission ID: 08b519c3-cfe9-4353-b429-7bc8d774e41d
Status: Completed
Submitted: May 11, 2021 20:50:54
User Opinion: Incorrect detection
Analyst comments:

We’ve reviewed your submission and we've confirmed that the submitted files are clean. Windows Defender Antivirus doesn't report them as malware.



The message you observed is a notification from Windows Defender SmartScreen indicating that the application does not have known reputation in our system. Application reputation warnings are meant to inform end users when applications do not have known positive reputation. This doesn’t mean that the application is malicious, only that it is “unknown”. Please note that users can still proceed to download and run the application.
