### ISSUE TITLE
Health based on file modification date

### ISSUE THREAD

**Issue by kata32** [grayfallstown/Chia-Plot-Status#33]
If I understand correctly the health field bases it on the modification date of the log file and this should work in most cases. In my configuration the log file is written to a share on a nas, I don't know why but in this case the last modification date of the file always remains the same as the creation date. The program shows the alert (Dead?) when in reality the log is growing, couldn't you also base it on this aspect?

**Comment by grayfallstown** [comment]
In the newest version these files will be shown as Dead when you open Chia Plot Status as it has no information that says otherwise at that moment. When the log continues to grow Chia Plot Status will pick that up and handle it correctly.

**Comment by kata32** [comment]
Hi,
as you say when the log is changed the "dead" warning disappears but few seconds later it returns with the same high numbers as before, may be you don't reset some kind of counter?

**Comment by grayfallstown** [comment]
Cannot disable last modfied at updates without a reboot and I'm plotting..

Try this [Setup.exe](https://grayfallstown.github.io/Chia-Plot-Status/index.md)

**Comment by kata32** [comment]
Your link point to index.md

**Comment by grayfallstown** [comment]
Fixed the link

**Comment by kata32** [comment]
> Cannot disable last modfied at updates without a reboot and I'm plotting..

Ok, I try for you.

With the setup provided no appreciable changes seen

**Comment by grayfallstown** [comment]
Found an error: [Setup.exe](http://grayfallstown.github.io/Chia-Plot-Status/Setup-issue33-2.exe)

**Comment by kata32** [comment]
You solved!

thank's
