### ISSUE TITLE
Error while installing deb file missing Packages

### ISSUE THREAD

**Issue by Jonesyj83** [grayfallstown/Chia-Plot-Status#38]
Have tried installing some but libcurl4 has replaced libcurl3

libicu is now libicu66 

libssl is now libssl1.1

Any Help would be great
Running on Ubuntu 20.04

`Selecting previously unselected package chiaplotstatus.
(Reading database ... 208025 files and directories currently installed.)
Preparing to unpack ChiaPlotStatus.linux-x64.deb ...
Unpacking chiaplotstatus (0.9.8) ...
dpkg: dependency problems prevent configuration of chiaplotstatus:
 chiaplotstatus depends on libcurl3; however:
  Package libcurl3 is not installed.
 chiaplotstatus depends on libssl0.9.8 | libssl1.0.0 | libssl1.0.1 | libssl1.0.2; however:
  Package libssl0.9.8 is not installed.
  Package libssl1.0.0 is not installed.
  Package libssl1.0.1 is not installed.
  Package libssl1.0.2 is not installed.
 chiaplotstatus depends on libicu52 | libicu53 | libicu54 | libicu55 | libicu56 | libicu57 | libicu58 | libicu59; however:
  Package libicu52 is not installed.
  Package libicu53 is not installed.
  Package libicu54 is not installed.
  Package libicu55 is not installed.
  Package libicu56 is not installed.
  Package libicu57 is not installed.
  Package libicu58 is not installed.
  Package libicu59 is not installed.

dpkg: error processing package chiaplotstatus (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Errors were encountered while processing:
 chiaplotstatus
`

**Comment by vashero** [comment]
Same Problem here.

**Comment by grayfallstown** [comment]
I told the tool I use to create this packages (not handcrafted) to target ubuntu 20 specifically and replaced the deb file.

Can you guys redownload the deb file and try again?
https://github.com/grayfallstown/Chia-Plot-Status/releases/download/0.9.8/ChiaPlotStatus.linux-x64.deb

**Comment by vashero** [comment]
same

**Comment by grayfallstown** [comment]
Just installed this version in my ubuntu vm:
https://github.com/grayfallstown/Chia-Plot-Status/releases/download/0.9.8/ChiaPlotStatus.linux-x64.deb

**Comment by vashero** [comment]
That one Works for me, Thanks!

**Comment by grayfallstown** [comment]
https://github.com/grayfallstown/Chia-Plot-Status/releases/download/0.9.8/ChiaPlotStatus.linux-x64.deb

**Comment by Jonesyj83** [comment]
Yeah same, it installs but not sure how to run it. Can't find chiaplotstatus anywhere

**Comment by grayfallstown** [comment]
> Yeah same, it installs but not sure how to run it. Can't find chiaplotstatus anywhere

Redownload, reinstall, then there is an icon in the menu

**Comment by vashero** [comment]
Works now thanks

**Comment by Jonesyj83** [comment]
Ahh cheers. Didn't think to look in the menu

**Comment by revantjhalani** [comment]
sudo apt install ./ChiaPlotStatus.linux-x64.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'chiaplotstatus' instead of './ChiaPlotStatus.linux-x64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 chiaplotstatus : Depends: libicu66 but it is not installable or
                           libicu65 but it is not installable or
                           libicu64 but it is not installable or
                           libicu63 but it is not installable or
                           libicu62 but it is not installable or
                           libicu61 but it is not installable or
                           libicu60 but it is not installable or
                           libicu59 but it is not installable or
                           libicu58 but it is not installable or
                           libicu57 but it is not installable or
                           libicu56 but it is not installable or
                           libicu55 but it is not installable or
                           libicu54 but it is not installable or
                           libicu53 but it is not installable or
                           libicu52 but it is not installable
E: Unable to correct problems, you have held broken packages.
