### ISSUE TITLE
Plot doesnt appear

### ISSUE THREAD

**Issue by dvlzgrmz** [grayfallstown/Chia-Plot-Status#41]
Hi! I am using the Chia-Plot-Status Programm since yesterday. Since them it showed all plots i made, but now i have made an new plot (actual 9% in chia gui) but it doesnt is shown in the chia-plot-status programm.
The log file is there and in the same folder, like all other plots, but it doesnt apears in the programm. can i manually select plot files to be shown in the programm?

**Comment by grayfallstown** [comment]
Can you publish the log file so I can take a look why this is not picked up?

**Comment by dvlzgrmz** [comment]
[plotter_log_f4282a09-fe55-470c-891a-618dcb9efc7d.txt](https://github.com/grayfallstown/Chia-Plot-Status/files/6478941/plotter_log_f4282a09-fe55-470c-891a-618dcb9efc7d.txt)

**Comment by grayfallstown** [comment]
Thank you for that log file.

The reason its not showing up is Chia Plot Status tries to probe each file before it parses it as a log file to prevent reading dozens of MB or GB if the user tells Chia Plot Status to use the wrong directory (like a plot directory with multiple 100GB of plots). It reads the first 1024 bytes of every file, converts it to text and looks for "Starting plotting progress into temporary dirs".

In your log you got a warning:
```
2021-05-14T13:03:30.100  chia.plotting.create_plots       : [32mINFO    [0m NOT adding directory I:\Plot-4150 to harvester for farming[0m
2021-05-14T13:03:30.100  chia.plotting.create_plots       : [33mWARNING [0m Directory I:\Plot-4150 already exists for harvester, please remove it manually[0m
```
These pushed the key sentence far enough down that is was no longer in the first 1024 bytes.

Currently building a fix for that.

**Comment by grayfallstown** [comment]
Version 0.9.10 is released

**Comment by dvlzgrmz** [comment]
BIG thanks to you! it works now
