### ISSUE TITLE
File lock on log files

### ISSUE THREAD

**Issue by kosztyua** [grayfallstown/Chia-Plot-Status#43]
Hi,
I have encountered an issue, possibly due to the way I want my setup to work, but maybe you can help solving it. As my plotter is a headless linux and really don't want to use that for this kind of interactive statistics, I want to move regularly the log files to my desktop and run your software for monitoring. 
Now the issue is that Chia-Plot-Status puts a lock on the log files and SCP cannot update/sync with the changes. Would it be possible to only read the files and not lock them permanently? I am not a programmer and not really adept with .NET

Using 3703a751323a9fcbf2b13bd7a52a224f62e01428 commit

**Comment by grayfallstown** [comment]
This comment should help: [chia plot status preventing files from updating in syncthing #40](https://github.com/grayfallstown/Chia-Plot-Status/issues/40#issuecomment-841025993)

**Comment by kosztyua** [comment]
Perfect answer, thank you!
