### ISSUE TITLE
Add notes to logfile to compare them better

### ISSUE THREAD

**Issue by rcamarda390** [grayfallstown/Chia-Plot-Status#44]
Id like ability to have brief notes show in CPS, that I add to log file. 
1. add tag to log file that CPS picks up 
2. add comment after tag
3. CPS shows note on display as comment

use case, computer tuning, or disk configuration testing (raid, caching) to help compare execution results of chia
Thanks!

**Comment by grayfallstown** [comment]
You could only add a tag/note to a logfile when the plotting process is finished, as the plotter write locks the file. Chia Plot Status keeps the log files open with a shared access by default as well, also preventing edits to the log files.
I could save the tags/notes separate of the log files in the Chia Plot Status config file, where manual death marks are already persisted.

**Comment by grayfallstown** [comment]
In the next Release.

**Comment by grayfallstown** [comment]
Released
