### ISSUE TITLE
Pause Refresh Button

### ISSUE THREAD

**Issue by raf-cr** [grayfallstown/Chia-Plot-Status#45]
Hi.
Great work.
App is refreshing constantly and then when i have scrolled down view ( multiple plots) every times its going to up.
It's little annoying, as i cant review fully logs as it still refreshing view.
Can be nice if will be button to turn off refresh , then i can able to review logs.

Also marked as dead is working bad, should be button mark ALL possible dead as dead.

Thank you.

**Comment by grayfallstown** [comment]
The pause refresh button will be in the next release.
The marked as dead problem wil be continued in issue #39.

**Comment by grayfallstown** [comment]
0.9.12 released.
