### ISSUE TITLE
Windows defender detects dll file as Trojan:Win32/Email.A!cl

### ISSUE THREAD

**Issue by vese** [grayfallstown/Chia-Plot-Status#46]
![image](https://user-images.githubusercontent.com/17708516/118499960-0f6c4880-b730-11eb-8f17-ce9ac89e35d6.png)

**Comment by grayfallstown** [comment]
[Same problem as last time](https://github.com/grayfallstown/Chia-Plot-Status/issues/2#issuecomment-839466951) I guess.

You can submit it for a manual scan by microsofts malware analysts if you want to know for sure: https://www.microsoft.com/en-us/wdsi/filesubmission
