### ISSUE TITLE
Microsoft Defender Antivirus reports Trojan:Win32/Emali.A!cl in ChiaPlotStatus\Avalonia.Win32.dll

### ISSUE THREAD

**Issue by jshank** [grayfallstown/Chia-Plot-Status#47]
Launched Chia Plot Status this morning and received a Microsoft Defender Antivirus alert that

 `C:\Program Files (x86)\ChiaPlotStatus\ChiaPlotStatus\Avalonia.Win32.dll` 

contains Trojan:Win32/Emali.A!cl. 

Likely a false positive but wanted to flag the issue.

**Comment by grayfallstown** [comment]
Thanks for the report.

I submitted the file in question to microsoft for a manual check by their analysts.

Guess its the same as the [other times](https://github.com/grayfallstown/Chia-Plot-Status/issues/2#issuecomment-839466951) it got a false positive.

The problematic part is that this file is part of an [external library](https://avaloniaui.net/) which is outside of my control. The good thing is, it got checked by microsofts and malwarebytes analysts as part of the Chia Plot Status Setup.exe before and got a green light.

**Comment by jshank** [comment]
Virustotal also shows [no threats](https://www.virustotal.com/gui/file/6666de3448365331bd4cc8a2ab67d811d8e345711cd5b847e17eb852e3b2be95/detection) for this file. Thanks for confirming.

**Comment by ouoam** [comment]
I try to update avalonia.win32 to lasted version (0.10.4). And than Microsoft Defender did not detect as virus.

**Comment by grayfallstown** [comment]
I updated AvaloniaUI and am currently building a new release. thanks @ouoam

**Comment by grayfallstown** [comment]
Also note https://github.com/AvaloniaUI/Avalonia/issues/5937

**Comment by grayfallstown** [comment]
```
avalonia.win32.dll
Submission ID: 2e5978b5-3b0c-414b-9e30-33e2407c3194
Status: Completed
Submitted: May 17, 2021 17:24:14
User Opinion: PuaFalsePositive
Analyst comments:

We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.

1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
3. Run "MpCmdRun.exe -SignatureUpdate"

Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions

Thank you for contacting Microsoft.
```
