### ISSUE TITLE
Virus Thread

### ISSUE THREAD

**Issue by gringomxstar** [grayfallstown/Chia-Plot-Status#48]
Hi,
Great Work thank you!
Is this normal?
The following Virus Warning shows up as follows:
C:\Program Files (x86)\ChiaPlotStatus\ChiaPlotStatus\Avalonia.Win32.dll 
Trojan:Win32/Emali.A!cl

**Comment by grayfallstown** [comment]
Thanks for the report.
Duplicate of #47, so closing this for now.
