### ISSUE TITLE
unable to load libSkiaSharp

### ISSUE THREAD

**Issue by ariegrossman** [grayfallstown/Chia-Plot-Status#55]
What does this mean? AM I missing a dependency?

./Chia-Plot-Status/ChiaPlotStatusGUI/bin/Release/net5.0/ChiaPlotStatus 
Unhandled exception. System.TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibSkiaSharp: cannot open shared object file: No such file or directory

**Comment by grayfallstown** [comment]
Any Update?

**Comment by grayfallstown** [comment]
Closed due to inactivity
