### ISSUE TITLE
"Your operating system is not supported." error

### ISSUE THREAD

**Issue by sirdeekay** [grayfallstown/Chia-Plot-Status#56]
I immediately get the message ""Your operating system is not supported." when I run setup.exe on Windows Server 2012 R2 x64.
Is there a reason for this or am I missing a prerequisite maybe?

**Comment by grayfallstown** [comment]
> I just compiled it myself and it seems to be working fine on 2012 R2 x64 - seems it's just the installer that is limiting it.

Should be fixed in the next release.

**Comment by sirdeekay** [comment]
> 
> 
> Released. I don't have Windows Server 2012 to test, can you please try the update?

Yes the installer is working fine now, thanks for the quick fix!
