### ISSUE TITLE
Enhancement: View Real Time Workingspace

### ISSUE THREAD

**Issue by whitetechnologies** [grayfallstown/Chia-Plot-Status#64]
It would be great if you could see what is the current workingspace for each paralell plot. This could help optimize plotting in paralell. 

For example, I have a 1TB SSD and can safely run 3 plots in paralell (staggered to optimize CPU/RAM usage). However, I know it is possible to run a 4th plot but it has to be timed correctly so it doesn't overfille the SSD. 

There was someone that tracked it here: 

https://www.reddit.com/r/chia/comments/mbjwbf/simple_plotting_resource_usage_graph/

It would be awesome if we can see or store the same type of information through Chia Plot Status

Great work keep it up!

**Comment by grayfallstown** [comment]
Chia Plot Status is meant to be used to monitor multiple machines at once and this would only be possible for plots that are generated on the same system as Chia Plot Status is running on. 

Chia Plot Status has no way to access the temp directories of all the other, possibly headless plotting rigs.

So this would only be possible if the information could be found in the logs.

**Comment by whitetechnologies** [comment]
Yes, you are right it seems a bit beyond the scope. However. I thought the logs did provide that info (where it says for example "Bucket 0 uniform sort 2.250Gib" etc. and if so, the log can use it. I'm happy to do a little more research on it to see if any info from the current logs is usuable in this way, as well as see if there's a chance additional resource usage can be added to logs

**Comment by grayfallstown** [comment]
`Bucket 104 uniform sort. Ram: 3.270GiB, u_sort min: 2.750GiB, qs min: 0.688GiB`

In order:
- Ram usable for sorting
- Minimal required RAM for uniform sort
- Minimal required RAM for quicksort

Have not found anything related to working space except at the end of the process.
