### ISSUE TITLE
Enhancement: View Plot # of # 

### ISSUE THREAD

**Issue by whitetechnologies** [grayfallstown/Chia-Plot-Status#65]
Many users typically run CLI with n > 1 so that one command will continuously create multiple plots in a row. Each time this command starts making a plot, it will say it's making a plot X of N. 

It would be very helpful if Plot Status can read that line, and show that in the Plot Status GUI dashboard. 

I think it's a very easy enhancement because it just needs to read that particular line and a new column

**Comment by grayfallstown** [comment]
In the new Release. For now new columns get added to the end. [Reorder the column as you like](https://github.com/grayfallstown/Chia-Plot-Status/issues/36#issuecomment-843351280)

**Comment by whitetechnologies** [comment]
Thank you, it's a very helpful update. However, it does not seem to read correctly

For example, I have 3 plots in paralell here and Chia Plot Status has read it as
24/1 (plots-E)
24/1 (plots-C)
12/1 (plots-D)

The actual logs show that we are on plot: 

Plot #24 out of 25 (plots-D)
Plot #24 out of 24 (plots-C)
Plot #12 out  of 25 (Plots-E)

I'm not sure if I'm missing something here or it's actually a bug. Appreciate the help as always!

**Comment by whitetechnologies** [comment]
Actual logs uploaded

[plots-5-7-2021-D.txt](https://github.com/grayfallstown/Chia-Plot-Status/files/6525611/plots-5-7-2021-D.txt)
[plots-5-7-2021-C.txt](https://github.com/grayfallstown/Chia-Plot-Status/files/6525612/plots-5-7-2021-C.txt)
[plots-5-7-2021-E.txt](https://github.com/grayfallstown/Chia-Plot-Status/files/6525613/plots-5-7-2021-E.txt)

**Comment by grayfallstown** [comment]
Where exactly is this line in the log files you provided?

**Comment by grayfallstown** [comment]
If you plot via powershell, replace `Tee-Object` with `2>&1 | % ToString | Tee-Object` and the missing lines should be added to the log.

**Comment by whitetechnologies** [comment]
This is a bit strange but it looks like the line does not appear in the log. It does appear in the live Powershell view (attached) but for some reason the Tee-Object does not capture it for some reason (I guess bc it's not considered part of the output of the process). I will try your suggestion as obviously that seems the correct way to capture it. Thank you! 

![Plotting-number](https://user-images.githubusercontent.com/39143124/119288015-c4fa3880-bc15-11eb-8e2c-e9b097b3af7d.jpg)
