### ISSUE TITLE
Log Delete

### ISSUE THREAD

**Issue by filzek** [grayfallstown/Chia-Plot-Status#66]
Hi, 

It shall be an amazing option to add a possibility of delete a log file, so upon a user choose the line it enable also the buttom to delete de log file, so it could recycle the logs and plots that has been problematic/canceled/breaked on creation.

Is that possible?

**Comment by filzek** [comment]
also an option to mark it as exclude shall worth and doest count on failed/others anymore, shall be simple but one problem more, as it doesnt save it status, once we restart application it will show again with the same problem, so, a log override shall be added to the controls to save choosen options to a file and once program open again it reads it and set the marks again on the logs found.

**Comment by grayfallstown** [comment]
Deleting the log files is more complicated than people think and is discussed in #39.

You can confirm that a plot if failed or dead by clicking on its health column and then click on "mark as dead". Then you can hide all plot logs that are confirmed dead. This is saved in the settings file if you have the current version.
