### ISSUE TITLE
Update feature shows wrong current version

### ISSUE THREAD

**Issue by RaySmalley** [grayfallstown/Chia-Plot-Status#67]
After upgrading from 0.9.10 to 0.9.13 I noticed that the update feature in the top left shows the currently installed version as 0.9.12.

![image](https://user-images.githubusercontent.com/16975199/119170632-86a42400-ba31-11eb-8bc0-fe8630ec161d.png)

I have the Windows version and confirmed 0.9.13 is installed.

**Comment by grayfallstown** [comment]
Thank you for reporting this.
I am pretty sure I know what caused this. Will be solved in the next release.
