### ISSUE TITLE
Content of log files in a mounted directory is not refreshing

### ISSUE THREAD

**Issue by htchaan** [grayfallstown/Chia-Plot-Status#68]
I am using this app on Windows 10 to read logs from an ubuntu machine.
If I open the log files with VS code and left them open, I can see the latest changes being appended to the file continuously, which is perfect.
However, if I have the Chia Plot Status app running and pointing to the same log directory at the same time, the files opened in VS code simply will not be refreshed anymore. As well as the status in Chia Plot Status app.

**Comment by grayfallstown** [comment]
How do you mount the folder? sshfs? samba?

Can you try this workaround: https://github.com/grayfallstown/Chia-Plot-Status/issues/40#issuecomment-841025993

**Comment by htchaan** [comment]
> How do you mount the folder? sshfs? samba?
> 
> Can you try this workaround: [#40 (comment)](https://github.com/grayfallstown/Chia-Plot-Status/issues/40#issuecomment-841025993)

I just share the log directories on Ubuntu and mount them on Windows directly through the OS's GUI. 
Tried the workaround to set `AlwaysDoFullRead` true with version 0.10.0, but it doesn't seem to work, still have to restart the app to see the latest log changes.

I am going to test more different samba configs / windows registry to see if I could get the entire caching thing disabled.

**Comment by grayfallstown** [comment]
@htchaan Have you found a way?
