### ISSUE TITLE
Show plotting statistics

### ISSUE THREAD

**Issue by RaySmalley** [grayfallstown/Chia-Plot-Status#70]
Column Moving: I would love it if I could drag columns left and right to where I desire. There's a lot of columns and scrolling to see what I want is a little annoying.

Average Time: Forgive me if this already exists, but it would be useful to have column that shows average plotting time for each plotter. I'm assuming you already do this in the background to determine if a plot is running "slow". It would be nice to see this for ourselves.

**Comment by revlisoft** [comment]
+1 and hiding columns.  Also to persist the column sizing during restarts as well.

**Comment by grayfallstown** [comment]
Reordering columns: https://github.com/grayfallstown/Chia-Plot-Status/issues/36#issuecomment-843351280

**Comment by grayfallstown** [comment]
There is a new Menu Entry for Statistics in the next release.

**Comment by grayfallstown** [comment]
This is in the 0.10.1 Release
