### ISSUE TITLE
Bug: setup.exe fails to install when stored on remote server/NAS

### ISSUE THREAD

**Issue by revlisoft** [grayfallstown/Chia-Plot-Status#72]
Setup fails when stored remotely and executed remotely.

**Comment by grayfallstown** [comment]
Was Chia Plot Status still running?
That is the main error why the setup fails.

**Comment by revlisoft** [comment]
I madd sure it was off before running. Might be some permissioning issue with running installs off a network share that has .net code?  However, I see that this is a msi packaged installer so a bit surprised. Once I copied it back locally it installed ok.

**Comment by grayfallstown** [comment]
Any Error Message?

**Comment by revlisoft** [comment]
![image](https://user-images.githubusercontent.com/4432112/119275119-44214980-bbe1-11eb-9f04-4d94983a8706.jpeg)

**Comment by grayfallstown** [comment]
Thanks for reporting this.

Maybe this could be fixed by switching to a different setup builder. I guess this is rare and easy enough to work around that I would not want to switch for now.

**Comment by revlisoft** [comment]
With the streamlined install this isn't worth enhancing anymore since it's just a one time action per PC. Previously I had 3 PCs so each update meant downloading it 3x times. I agree it should just stay closed with no action to be taken.
