### ISSUE TITLE
Enhancement: Update to be more seamless

### ISSUE THREAD

**Issue by revlisoft** [grayfallstown/Chia-Plot-Status#73]
An external update mechanism which would download, extract and run the install/update and cleanup afterwards.

**Comment by grayfallstown** [comment]
Currently the update download gets delegated to the default browser.
Could be done in Chia Plot Status instead.

Setup gets downloaded to a Chia Plot Status related subdirectory in temp.
User gets a notification dialog, telling him the update is ready and that the application needs to be closed to install the update.
User confirms or just plain closes the app as he did not read the buttons. -> register eventhandler in Window.Closed
Setup gets started.
Chia Plot Status stops itself.
At the end of the Setup Chia Plot Status gets started again. (already default)
Chia Plot Status checks for a Setup file in the temp subdir and deletes any if found.

**Comment by revlisoft** [comment]
Sounds like a perfect way to streamline the updates.

**Comment by grayfallstown** [comment]
Will be in the next release

**Comment by grayfallstown** [comment]
Released
