### ISSUE TITLE
Date format ignores locale settings and uses US format

### ISSUE THREAD

**Issue by wizbowes** [grayfallstown/Chia-Plot-Status#75]
Date times use the US format.  Please can you use the local datetime format.

**Comment by grayfallstown** [comment]
Since the Application is entirely in english I thought using the us date format would make sense but the more I look at it, the more it bothers me as well.

**Comment by grayfallstown** [comment]
Will be in the next Release.

**Comment by grayfallstown** [comment]
Released with 0.10.2
