### ISSUE TITLE
Cant update Linux version.

### ISSUE THREAD

**Issue by DazEB2** [grayfallstown/Chia-Plot-Status#77]
Trying to download the latest Linux deb file doesn't update. Seems to stay on version 0.9.9

**Comment by DazEB2** [comment]
No there is no Statistics menu only Update and Donate

**Comment by grayfallstown** [comment]
Booting up my Ubuntu VM to check this out.

**Comment by DazEB2** [comment]
Much appreciated, im using 20.04 desktop

**Comment by grayfallstown** [comment]
Please redownload and try again.

**Comment by DazEB2** [comment]
Will do now.

**Comment by grayfallstown** [comment]
Happy to help!
