### ISSUE TITLE
Show Queue Name from the Chia GUI Plotter

### ISSUE THREAD

**Issue by raf-cr** [grayfallstown/Chia-Plot-Status#79]
Hi again.
If app can show "Queue name" same like in chia app,   then its easier to identify plots by name, i need that to compare time with different settings :)

**Comment by grayfallstown** [comment]
I would love to add this for people who use the GUI to Plot, but it is not possible.

The queue name is not written to the log files. There is no way for an external tool like Chia Plot Status to find out what queue name you see in the Chia GUI.

**Comment by grayfallstown** [comment]
I already implemented an option to do that #44 

> So maybe option to add name manually?

I already implemented an option to do that #44. Will be in the next release. I can change this so the note applies to an entire queue.

> Its only GUI issue? With CLI its not a problem?

As far as I know `chia plots create` (on the CLI) does not know the queue name either.
