### ISSUE TITLE
Feature: Detect and Highlight crashed plotting processes

### ISSUE THREAD

**Issue by grayfallstown** [grayfallstown/Chia-Plot-Status#8]

**Comment by TormodSan** [comment]
Great feature - but should take into account phases.
e.g. in Phase 2
sorting table 6
sort time =  841.420 seconds. CPU (61.400%) Mon May  3 15:47:01 2021

there is no logging for 841 secs

**Comment by grayfallstown** [comment]
Good Idea
Currently still testing the timings

**Comment by grayfallstown** [comment]
Health check is considering phase statistics now, so you get earlier warnings on faster systems with fast SSDs than slow systems with HDDs and also considers Mixed SSDs/HDDs for different plots on the same system.
This requires existing finished plotlogs or it goes down to a diced default (not sure what values should be used yet).

**Comment by grayfallstown** [comment]
The user must be able to confirm a dead process.

Chia Plot Status can never be sure if the process is dead. Locally (and with admin rights) it could potentially check running processes and their file handles and check is the process this belongs to is still running, but Chia Plot Status is for multiple remote plotting rigs as well and we cannot do that via network share.

The user should still be able to get rid of dead logs without deleting the files as `create plot --num 18` can log all plots to the same file, depending how it is set up.

Thats why PlotLog needs an index telling this is the n-th log in the given file.
Then we can hide the 7th log in file b73b03ce-acba-11eb-8529-0242ac130003.log from folder rig-2 without throwing out the other logs as well, since finished plotlogs are needed to ETA and HealthCheck.

User should right click on a line and click "hide" or "confirm dead".

Which logs are hidden should be persisted in the users config file.

A different approach would be to have a watchdog on each plotting rig collecting the logs and watching the processes like described in the second paragraph and continously sends the logs and status to the monitor system (the pc running chia plot status GUI). Then we would know more and the user does not have to setup either a network share or a different approach to get to the logs of all his rigs. Again, this requires admin/root access and I do not want that for now but could be a future addition. Kubernetes did this last time I worked with it and its a common approach for distributed systems.

**Comment by grayfallstown** [comment]
If last line is `Final File size: 101.367 GiB` and final dir != tmp2 a 100 GB file is copied without logging a think. This takes a while and currently this can cause a `possibly dead` warning.
[Ticket 184](https://github.com/Chia-Network/chiapos/issues/184) in chiapos would fix that, but no idea when that is implemented

**Comment by grayfallstown** [comment]
> The user must be able to confirm a dead process.

The logic is implemented, gui part is still missing

**Comment by grayfallstown** [comment]
You can now confirm the death of a plotting process and then filter them out
