### ISSUE TITLE
Is there a way...

### ISSUE THREAD

**Issue by nanohtpc** [grayfallstown/Chia-Plot-Status#80]
To highlight various plots?

i want to compare performance, and see how ranks against others...

Greetings from PERU!

and also a found a bug.... i doesnt show the CPU util... in a working rig. but if i move the log to other machine IT SHOWS!!!

**Comment by grayfallstown** [comment]
> Greetings from PERU!

Greetings from Germany!

I think if I implement feature #44 you could do something like this.
Then you could add a tag to the relevant logs and use the search for it.

**Comment by grayfallstown** [comment]
#44 is in the next Release
