### ISSUE TITLE
Lists scroll to the top every 3-5 seconds

### ISSUE THREAD

**Issue by magnusmyklebost** [grayfallstown/Chia-Plot-Status#81]
When I scroll down the list over finished plots sorted by time finished to analyze the totalt time etc, the list automatically jumps to the top every 3-5 seconds. This is a bit annoying when you have scrolled down and found the plots of interest, and it just jumps to the top again.

Thanks for a great tool!

**Comment by grayfallstown** [comment]
Are you sure it is not every 10 Seconds?

This issue is known (#51) and I don't know how to fix that properly with the GUI Library I use.

There is a Button to pause refresh on the top right. That should allow you to analyse the data in peace.
