### ISSUE TITLE
Slows down Ubuntu computer, 100% cpu usage

### ISSUE THREAD

**Issue by hidoba** [grayfallstown/Chia-Plot-Status#84]
I'm using the latest version from Releases (0.10.2) on Ubuntu 20.04.2 LTS computer.
Every time I run the app everything in the computer GUI becomes very slow and not responsive.
chiaplotstatus uses 100% of the cpu thread at any time, according to htop.

**Comment by grayfallstown** [comment]
Just tried to reproduce this in an Ubuntu VM. This problem did not occure.

Please close Chia Plot Status, move `/home/<your username>/ChiaPlotStatu.config.json`. to `/home/<your username>/ChiaPlotStatu.config.json.bak` (you could execute `mv ~/ChiaPlotStatu.config.json ~/ChiaPlotStatu.config.json.bak` on your terminal without sudo to do this), start Chia Plot Status again and check if this happens again.

**Comment by hidoba** [comment]
Removed settings file, reopened, same problem with completely empty list (I didn't add the log folder).
I'm reluctant to restart my PC because of the ongoing plots, but I'll do it tomorrow and report if it helps.

**Comment by grayfallstown** [comment]
You could try another thing:

Close Chia Plot Status, go to ~/.chia/mainnet/plotter/ and without sudo (!) try to move all log files to a subfolder. This will only work for the files not currently being written by your plotters, which is intended.

If Chia Plot Status starts and works now, then start to move back some of the files every ten seconds until it shows 100% CPU usage again.

Take a look at the files you moved back last and check if there is anything unusual in them.
If you manage to identify a log file that causes this behaviour I would like to see it, so I can reproduce and fix this problem.

**Comment by hidoba** [comment]
I don't have a ~/.chia/mainnet/plotter folder, I use another folder for log files in my plotman settings. Maybe this is an issue?

**Comment by grayfallstown** [comment]
Using a different folder or plot manager should not cause this issue. You can still try the approach above, just with the other folder.

**Comment by hidoba** [comment]
After I removed the ChiaPlotStatus settings file, it should not know where my logs are stored. That's why after I open the app it displays empty table, still running extremely slowly.

**Comment by grayfallstown** [comment]
> After I removed the ChiaPlotStatus settings file, it should not know where my logs are stored

Right..

That actually makes it less likely that this is caused by a bug in the code I wrote. It is more likely a problem with the used gui library [AvaloniaUI](http://avaloniaui.net/) or the system and its drivers.

Is the computer directly connected to the monitor or are you accessing the system via X-Forwarding or any other form of remote desktop access?
Can you check if 2D/3D acceleration is running properly on your system?

**Comment by hidoba** [comment]
You may be right, I've noticed something funny with GPU driver, I was also mining on the GPU with a very low hashrate, and the nvidia tool is acting as if the driver crashed. Note the "ERR":
$ nvidia-smi 
Sat May 29 19:19:50 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.73.01    Driver Version: 460.73.01    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 3070    Off  | 00000000:2B:00.0  On |                  N/A |
|ERR!   38C    P0   ERR! / 220W |    177MiB /  7973MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+




this command gives no problem, although hangs all the graphics for a few seconds:
hidoba@plotter1:~/eth$ /usr/lib/nux/unity_support_test -p
OpenGL vendor string:   NVIDIA Corporation
OpenGL renderer string: GeForce RTX 3070/PCIe/SSE2
OpenGL version string:  4.6.0 NVIDIA 460.73.01

Not software rendered:    yes
Not blacklisted:          yes
GLX fbconfig:             yes
GLX texture from pixmap:  yes
GL npot or rect textures: yes
GL vertex program:        yes
GL fragment program:      yes
GL vertex buffer object:  yes
GL framebuffer object:    yes
GL version is 1.4+:       yes

Unity 3D supported:       yes


I'll restart the computer tomorrow and post the results.

**Comment by grayfallstown** [comment]
Any Update?

**Comment by hidoba** [comment]
reboot didn't help. I'll do a clean install on a separate drive because I also want to fix issue preventing me from mining on a GPU with normal hashrate.

**Comment by hidoba** [comment]
Works well with a clean install of Ubuntu. Is it possible that the slow down last time was caused because I installed the asp.net runtime libraries, not SDK?

**Comment by grayfallstown** [comment]
I think this would be unlikely but the only way to find out for sure is to try that again.
