### ISSUE TITLE
Log is being used by Chia Plot Status

### ISSUE THREAD

**Issue by JoseAngelB** [grayfallstown/Chia-Plot-Status#86]
Remove when I try to delete a failed log I get "The file is being used by Chia Plot Status" error, I have to close it, delete the file, and open it again.
Also, there are some plot managers that moves the logs when they are finished, and if Chia Plot Status is open, they fail to move or delete their own logs

**Comment by grayfallstown** [comment]
There is already a solution for this:
https://github.com/grayfallstown/Chia-Plot-Status#troubleshooting

Don't use this to delete finished log files or you will ruin ETA and warning threshold calculations.

**Comment by grayfallstown** [comment]
Which plot managers move log files?

**Comment by JoseAngelB** [comment]
https://github.com/abueide/harry-plotter
