### ISSUE TITLE
Low performance

### ISSUE THREAD

**Issue by bathrobehero** [grayfallstown/Chia-Plot-Status#88]
Hi! This recent release (0.10.3) further destroyed the performance for me. It uses 2.5GB of RAM, pegs a single CPU thread at 100% and took 9 minutes for the GUI to show. And even then it's very slow to react to pretty much anything.

Even in the search window, each character is like a 10 second lag. File open dialogs are taking like 5-10 second for every action.

Granted, this is with ~1400 plots but still, it's much worse than the last release - for me at least (windows, 8700k).

I really love the harvester health feature though! But it's only showing 656 plots instead of ~1400 that is in the single logfile it's reading from. There isn't a single instance in the log file for that amount of plots.

**Comment by grayfallstown** [comment]
Ok, I already know what caused this and how to fix it. Next version might be faster for you than 0.10.2 was.

**Comment by grayfallstown** [comment]
Try 0.10.4. First time starting the version takes a while, that then speed should improve.

**Comment by grayfallstown** [comment]
> But it's only showing 656 plots instead of ~1400 that is in the single logfile it's reading from.

First and Last log entry where mixed up.

> There isn't a single instance in the log file for that amount of plots.

It does load debug.log.1, debug.log.2, ... etc as well. In one of them you will find 656.

The idea is to make an overview about current state and a separate view over the entire historic data. It is all still work in progress.

**Comment by bathrobehero** [comment]
Everything's solved. Cheers!
