### ISSUE TITLE
Enhancement: Option in config to drop/round the seconds up from the time calcs

### ISSUE THREAD

**Issue by lifeline143** [grayfallstown/Chia-Plot-Status#89]
The seconds in the Phase time calculations come straight from the log files I know, but the addition of them on the screen is really pretty significant visual clutter in being able to quickly scan times.  The only phases where it provides useful info is in phase 4 & 5 where 60 secs is pretty big chunk of total phase time.

Suggestion: provide a config option allowing to round the second calculations up to the next minute for phase 1 thru 3 and total time.  Alternatively, could enable option to disable in 4/5 separately as well, but biggest gain is in the first 3 phases and total time for reducing the visual business.

Thanks for the consideration,
Scott

**Comment by grayfallstown** [comment]
Implemented in Version 0.10.5.
Without a config option. Could be added later if requested.
