### ISSUE TITLE
Avalonia Library flagged as Trojan (currently being analysed by microsoft)

### ISSUE THREAD

**Issue by nanohtpc** [grayfallstown/Chia-Plot-Status#91]
something called emaili...

could you check please...

latest version btw

**Comment by grayfallstown** [comment]
likely a false positive [again](https://github.com/grayfallstown/Chia-Plot-Status/issues/2).
Checking..

**Comment by nanohtpc** [comment]
windows defender
roguekiller

**Comment by maxbegin** [comment]
![image](https://user-images.githubusercontent.com/37770070/120627990-c8ec4d00-c496-11eb-8c6f-0375736de113.png)

**Comment by nanohtpc** [comment]
same

**Comment by grayfallstown** [comment]
Submitted for manual review by Microsofts Malware Analysts over their [webportal](https://www.microsoft.com/en-us/wdsi/filesubmission) yet again.

It will take some time for them to respond.

Personally I am not afraid having Chia Plot Status with its dependency on the [avalonia ui library](https://avaloniaui.net/) installed and running on my system, just massively annoyed as Chia Plot Status or one of its dependencies falsely getting flagged and then marked as safe/clean/clear by Microsofts Malware Analysts after a manual checkup happens [way too often](https://github.com/grayfallstown/Chia-Plot-Status/issues/2). I guess its their AI that goes rogue.

### Submission:

Company name
none, open source dev

Do you have a Microsoft support case number?
NoSupport case number
No information provided

Product
Microsoft Defender Antivirus (Windows 10)

Submission priority
Regular

File
Avalonia.Win32.dll (352 KB)

Removal date
June 03, 2026

What do you believe this file is?
Incorrectly detected as malware/malicious

Detection name
Trojan:Win32/Emali.A!cl

Definition version
1.339.1937.0

Additional information
Part of avalonia ui library https://avaloniaui.net/ version 0.10.5 Avalonia dll files got repeatedly detected by windows defender and then given clear status by you guys basically every 3 to 5 days over the last three weeks. Almost everytime with a different detection name.


### I submitted avalonia.themes.fluent.dll too, as it got flagged on my system as well.

**Comment by grayfallstown** [comment]
I added a note to the download section to inform users about this.

**Comment by grayfallstown** [comment]
One of two files marked as clean again.

Submission details
avalonia.win32.dll
Submission ID: 91833e65-8d89-4c11-8960-8e1a0c501c19
Status: Completed
Submitted: Jun 3, 2021 12:20:18
User Opinion: Incorrect detection
Analyst comments:

We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.

1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
3. Run "MpCmdRun.exe -SignatureUpdate"

Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions

**Comment by grayfallstown** [comment]
Avalonia.Themes.Fluent.dll is no longer detected on my system or VirusTotal as well. I did not receive the result of the submission yet.

**Comment by grayfallstown** [comment]
avalonia.controls.datagrid.dll
Submission ID: 49cbc87f-29e2-4e24-8439-e569f48cdefd
Status: Completed
Submitted: Jun 3, 2021 20:01:01
User Opinion: Incorrect detection
Analyst comments:

We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.

1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
3. Run "MpCmdRun.exe -SignatureUpdate"

Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions

Thank you for contacting Microsoft.

**Comment by grayfallstown** [comment]
So, all files are safe, considered safe by Windows Defender with the latest updates. Closing this.
