### ISSUE TITLE
Harvester Tab not picking up new plots

### ISSUE THREAD

**Issue by blood5322** [grayfallstown/Chia-Plot-Status#93]
When I started using the application yesterday it has the total plots in the harvester correct. However after finishing 8 more plots the total plots isn't updating. I've checked my debug log and the total in there has changed. I've tried removing and re-adding the path to the log with no success. I'm running on Ubuntu 20.04.

**Comment by grayfallstown** [comment]
Already fixed.
I will release that now.

**Comment by grayfallstown** [comment]
Try updating

**Comment by blood5322** [comment]
Yep that did it! Thanks for quick turnaround!
