### ISSUE TITLE
Visual Studio Code Error 

### ISSUE THREAD

**Issue by majnouni** [grayfallstown/Chia-Plot-Status#99]
This message is displayed when I want to run the code in VisualStudio 
![Eror](https://user-images.githubusercontent.com/34125969/121740074-caaab600-cb11-11eb-8868-1972c0b7f800.jpg)
g)

**Comment by grayfallstown** [comment]
Make sure you have .net 5 sdk installed.

**Comment by grayfallstown** [comment]
Did installing .net 5 sdk solve this for you?
